# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd9b3c3aee8d85bb559481762dcfeaecbb5d69f35d6b90173e5af4df4c45295608ac367f9dee8792a8d72a3ac5e72456e22815670ab330df7d857b3a66a86e81

test:
  secret_key_base: b5ce1febd124fac944121dce832a4d0a8e9f728721e3286a6180dd587e7ff20fb77148ca5b5b660c64c76e7c431a8966659581319115a320e3019305c4568e3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
